### ISSUE TITLE
模型调用

### ISSUE THREAD

**Issue by winnermiao** [EnrigleZ/pakt#1]
您好，拜读了您的论文，收获很大。现在有个问题想请教您一下，如何调用已经训练好的模型在测试数据集上运行呢？如果直接运行程序，得到的是test-AUC吗？

**Comment by EnrigleZ** [comment]
是的，运行之后可以观察每个epoch的输出，为了方便输出，每个epoch在训练后分别输出交叉验证集和测试集的AUC

**Comment by winnermiao** [comment]
十分感谢您的回答！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "EnrigleZ/pakt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月3日(星期二) 晚上10:08
***@***.***&gt;;
抄送:&nbsp;" ***@***.******@***.***&gt;;
主题:&nbsp;Re: [EnrigleZ/pakt] 模型调用 (#1)





 
是的，运行之后可以观察每个epoch的输出，为了方便输出，每个epoch在训练后分别输出交叉验证集和测试集的AUC
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
